// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  username: __t.string(),
  usernameKey: __t.string().name("username_key"),
  colorIndex: __t.u8().name("color_index"),
  roundsPlayed: __t.u32().name("rounds_played"),
  wins: __t.u32(),
  piecesPlaced: __t.u32().name("pieces_placed"),
  createdAt: __t.timestamp().name("created_at"),
});
