// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  kind: __t.string(),
  actorName: __t.string().name("actor_name"),
  colorIndex: __t.u8().name("color_index"),
  pieceKind: __t.string().name("piece_kind"),
  tileX: __t.u8().name("tile_x"),
  tileZ: __t.u8().name("tile_z"),
});
