// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  lobbySeconds: __t.u32().name("lobby_seconds"),
  buildSeconds: __t.u32().name("build_seconds"),
  scoringSeconds: __t.u32().name("scoring_seconds"),
  votingSeconds: __t.u32().name("voting_seconds"),
  resultsSeconds: __t.u32().name("results_seconds"),
});
