// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  lobbySeconds: __t.u32(),
  buildSeconds: __t.u32(),
  scoringSeconds: __t.u32(),
  votingSeconds: __t.u32(),
  resultsSeconds: __t.u32(),
  showcaseSeconds: __t.u32(),
};
