// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Phase,
  Mode,
} from "./types";


export default __t.row({
  islandId: __t.u64().primaryKey().name("island_id"),
  get phase() {
    return Phase;
  },
  get mode() {
    return Mode;
  },
  round: __t.u32(),
  themeTitle: __t.string().name("theme_title"),
  challengeId: __t.u8().name("challenge_id"),
  host: __t.option(__t.identity()),
  phaseStartedAt: __t.timestamp().name("phase_started_at"),
  phaseEndsAt: __t.option(__t.timestamp()).name("phase_ends_at"),
  teamScore: __t.u32().name("team_score"),
  showcaseBoard: __t.u8().name("showcase_board"),
});
