// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "./accept_friend_request_reducer";
import ConfigureTimingReducer from "./configure_timing_reducer";
import CreateAccountReducer from "./create_account_reducer";
import CreateIslandReducer from "./create_island_reducer";
import DeclineFriendRequestReducer from "./decline_friend_request_reducer";
import DeleteBuildReducer from "./delete_build_reducer";
import EnterIslandReducer from "./enter_island_reducer";
import LeaveIslandReducer from "./leave_island_reducer";
import LoadBuildReducer from "./load_build_reducer";
import MoveReducer from "./move_reducer";
import NewRecoveryCodeReducer from "./new_recovery_code_reducer";
import PlacePieceReducer from "./place_piece_reducer";
import RecoverAccountReducer from "./recover_account_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import RemovePieceReducer from "./remove_piece_reducer";
import ResetGameReducer from "./reset_game_reducer";
import RotatePieceReducer from "./rotate_piece_reducer";
import SaveBuildReducer from "./save_build_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SetNameReducer from "./set_name_reducer";
import SkipPhaseReducer from "./skip_phase_reducer";
import StartRoundReducer from "./start_round_reducer";
import SubmitIdeaReducer from "./submit_idea_reducer";
import VotePlotReducer from "./vote_plot_reducer";
import VoteThemeReducer from "./vote_theme_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountRow from "./account_table";
import ActivityRow from "./activity_table";
import ConfigRow from "./config_table";
import FriendRequestRow from "./friend_request_table";
import FriendshipRow from "./friendship_table";
import GameStateRow from "./game_state_table";
import IdeaRow from "./idea_table";
import IslandRow from "./island_table";
import MyRecoveryCodeRow from "./my_recovery_code_table";
import PieceRow from "./piece_table";
import PlayerRow from "./player_table";
import PlotRow from "./plot_table";
import PlotVoteRow from "./plot_vote_table";
import RoundResultRow from "./round_result_table";
import SavedBuildRow from "./saved_build_table";
import ThemeVoteRow from "./theme_vote_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  account: __table({
    name: 'account',
    indexes: [
      { accessor: 'id', name: 'account_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'account_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
      { accessor: 'usernameKey', name: 'account_username_key_idx_btree', algorithm: 'btree', columns: [
        'usernameKey',
      ] },
    ],
    constraints: [
      { name: 'account_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'account_owner_key', constraint: 'unique', columns: ['owner'] },
      { name: 'account_username_key_key', constraint: 'unique', columns: ['usernameKey'] },
    ],
  }, AccountRow),
  activity: __table({
    name: 'activity',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, ActivityRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'id', name: 'config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConfigRow),
  friendRequest: __table({
    name: 'friend_request',
    indexes: [
      { accessor: 'fromAccountId', name: 'friend_request_from_account_id_idx_btree', algorithm: 'btree', columns: [
        'fromAccountId',
      ] },
      { accessor: 'id', name: 'friend_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'pairKey', name: 'friend_request_pair_key_idx_btree', algorithm: 'btree', columns: [
        'pairKey',
      ] },
      { accessor: 'toAccountId', name: 'friend_request_to_account_id_idx_btree', algorithm: 'btree', columns: [
        'toAccountId',
      ] },
    ],
    constraints: [
      { name: 'friend_request_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'friend_request_pair_key_key', constraint: 'unique', columns: ['pairKey'] },
    ],
  }, FriendRequestRow),
  friendship: __table({
    name: 'friendship',
    indexes: [
      { accessor: 'accountA', name: 'friendship_account_a_idx_btree', algorithm: 'btree', columns: [
        'accountA',
      ] },
      { accessor: 'accountB', name: 'friendship_account_b_idx_btree', algorithm: 'btree', columns: [
        'accountB',
      ] },
      { accessor: 'id', name: 'friendship_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'pairKey', name: 'friendship_pair_key_idx_btree', algorithm: 'btree', columns: [
        'pairKey',
      ] },
    ],
    constraints: [
      { name: 'friendship_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'friendship_pair_key_key', constraint: 'unique', columns: ['pairKey'] },
    ],
  }, FriendshipRow),
  gameState: __table({
    name: 'game_state',
    indexes: [
      { accessor: 'islandId', name: 'game_state_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
    ],
    constraints: [
      { name: 'game_state_island_id_key', constraint: 'unique', columns: ['islandId'] },
    ],
  }, GameStateRow),
  idea: __table({
    name: 'idea',
    indexes: [
      { accessor: 'author', name: 'idea_author_idx_btree', algorithm: 'btree', columns: [
        'author',
      ] },
      { accessor: 'id', name: 'idea_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'islandId', name: 'idea_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
    ],
    constraints: [
      { name: 'idea_author_key', constraint: 'unique', columns: ['author'] },
      { name: 'idea_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IdeaRow),
  island: __table({
    name: 'island',
    indexes: [
      { accessor: 'id', name: 'island_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ownerAccountId', name: 'island_owner_account_id_idx_btree', algorithm: 'btree', columns: [
        'ownerAccountId',
      ] },
    ],
    constraints: [
      { name: 'island_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IslandRow),
  piece: __table({
    name: 'piece',
    indexes: [
      { accessor: 'cellKey', name: 'piece_cell_key_idx_btree', algorithm: 'btree', columns: [
        'cellKey',
      ] },
      { accessor: 'id', name: 'piece_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'islandId', name: 'piece_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
      { accessor: 'placedBy', name: 'piece_placed_by_idx_btree', algorithm: 'btree', columns: [
        'placedBy',
      ] },
    ],
    constraints: [
      { name: 'piece_cell_key_key', constraint: 'unique', columns: ['cellKey'] },
      { name: 'piece_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PieceRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'islandId', name: 'player_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  plot: __table({
    name: 'plot',
    indexes: [
      { accessor: 'builder', name: 'plot_builder_idx_btree', algorithm: 'btree', columns: [
        'builder',
      ] },
      { accessor: 'id', name: 'plot_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'islandId', name: 'plot_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
      { accessor: 'plotKey', name: 'plot_plot_key_idx_btree', algorithm: 'btree', columns: [
        'plotKey',
      ] },
    ],
    constraints: [
      { name: 'plot_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'plot_plot_key_key', constraint: 'unique', columns: ['plotKey'] },
    ],
  }, PlotRow),
  plotVote: __table({
    name: 'plot_vote',
    indexes: [
      { accessor: 'islandId', name: 'plot_vote_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
      { accessor: 'voter', name: 'plot_vote_voter_idx_btree', algorithm: 'btree', columns: [
        'voter',
      ] },
    ],
    constraints: [
      { name: 'plot_vote_voter_key', constraint: 'unique', columns: ['voter'] },
    ],
  }, PlotVoteRow),
  roundResult: __table({
    name: 'round_result',
    indexes: [
      { accessor: 'id', name: 'round_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'islandId', name: 'round_result_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
    ],
    constraints: [
      { name: 'round_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoundResultRow),
  savedBuild: __table({
    name: 'saved_build',
    indexes: [
      { accessor: 'id', name: 'saved_build_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ownerAccountId', name: 'saved_build_owner_account_id_idx_btree', algorithm: 'btree', columns: [
        'ownerAccountId',
      ] },
    ],
    constraints: [
      { name: 'saved_build_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SavedBuildRow),
  themeVote: __table({
    name: 'theme_vote',
    indexes: [
      { accessor: 'islandId', name: 'theme_vote_island_id_idx_btree', algorithm: 'btree', columns: [
        'islandId',
      ] },
      { accessor: 'voter', name: 'theme_vote_voter_idx_btree', algorithm: 'btree', columns: [
        'voter',
      ] },
    ],
    constraints: [
      { name: 'theme_vote_voter_key', constraint: 'unique', columns: ['voter'] },
    ],
  }, ThemeVoteRow),
  myRecoveryCode: __table({
    name: 'my_recovery_code',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecoveryCodeRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_friend_request", AcceptFriendRequestReducer),
  __reducerSchema("configure_timing", ConfigureTimingReducer),
  __reducerSchema("create_account", CreateAccountReducer),
  __reducerSchema("create_island", CreateIslandReducer),
  __reducerSchema("decline_friend_request", DeclineFriendRequestReducer),
  __reducerSchema("delete_build", DeleteBuildReducer),
  __reducerSchema("enter_island", EnterIslandReducer),
  __reducerSchema("leave_island", LeaveIslandReducer),
  __reducerSchema("load_build", LoadBuildReducer),
  __reducerSchema("move", MoveReducer),
  __reducerSchema("new_recovery_code", NewRecoveryCodeReducer),
  __reducerSchema("place_piece", PlacePieceReducer),
  __reducerSchema("recover_account", RecoverAccountReducer),
  __reducerSchema("remove_friend", RemoveFriendReducer),
  __reducerSchema("remove_piece", RemovePieceReducer),
  __reducerSchema("reset_game", ResetGameReducer),
  __reducerSchema("rotate_piece", RotatePieceReducer),
  __reducerSchema("save_build", SaveBuildReducer),
  __reducerSchema("send_friend_request", SendFriendRequestReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("skip_phase", SkipPhaseReducer),
  __reducerSchema("start_round", StartRoundReducer),
  __reducerSchema("submit_idea", SubmitIdeaReducer),
  __reducerSchema("vote_plot", VotePlotReducer),
  __reducerSchema("vote_theme", VoteThemeReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

