// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  islandId: __t.u64().name("island_id"),
  cellKey: __t.u64().name("cell_key"),
  tileKey: __t.u32().name("tile_key"),
  tileX: __t.u8().name("tile_x"),
  tileZ: __t.u8().name("tile_z"),
  kind: __t.string(),
  rotation: __t.u8(),
  placedBy: __t.identity().name("placed_by"),
  placedAt: __t.timestamp().name("placed_at"),
  round: __t.u32(),
});
