// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  islandId: __t.u64().name("island_id"),
  name: __t.string(),
  colorIndex: __t.u8().name("color_index"),
  online: __t.bool(),
  x: __t.f32(),
  z: __t.f32(),
  heading: __t.f32(),
  moveBudget: __t.f32().name("move_budget"),
  lastMoveAt: __t.timestamp().name("last_move_at"),
});
