// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SavedPiece,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  ownerAccountId: __t.u64().name("owner_account_id"),
  name: __t.string(),
  get pieces() {
    return __t.array(SavedPiece);
  },
  createdAt: __t.timestamp().name("created_at"),
});
