// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameState = __t.object("GameState", {
  id: __t.u8(),
  get phase() {
    return Phase;
  },
  round: __t.u32(),
});
export type GameState = __Infer<typeof GameState>;

// The tagged union or sum type for the algebraic type `Phase`.
export const Phase = __t.enum("Phase", {
  Lobby: __t.unit(),
  Building: __t.unit(),
  Scoring: __t.unit(),
  Results: __t.unit(),
});
export type Phase = __Infer<typeof Phase>;

