// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Activity = __t.object("Activity", {
  kind: __t.string(),
  actorName: __t.string(),
  colorIndex: __t.u8(),
  pieceKind: __t.string(),
  tileX: __t.u8(),
  tileZ: __t.u8(),
});
export type Activity = __Infer<typeof Activity>;

export const GameState = __t.object("GameState", {
  id: __t.u8(),
  get phase() {
    return Phase;
  },
  round: __t.u32(),
});
export type GameState = __Infer<typeof GameState>;

// The tagged union or sum type for the algebraic type `Phase`.
export const Phase = __t.enum("Phase", {
  Lobby: __t.unit(),
  Building: __t.unit(),
  Scoring: __t.unit(),
  Results: __t.unit(),
});
export type Phase = __Infer<typeof Phase>;

export const Piece = __t.object("Piece", {
  id: __t.u64(),
  tileKey: __t.u32(),
  tileX: __t.u8(),
  tileZ: __t.u8(),
  kind: __t.string(),
  rotation: __t.u8(),
  placedBy: __t.identity(),
  placedAt: __t.timestamp(),
  round: __t.u32(),
});
export type Piece = __Infer<typeof Piece>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  colorIndex: __t.u8(),
  online: __t.bool(),
  x: __t.f32(),
  z: __t.f32(),
  heading: __t.f32(),
  moveBudget: __t.f32(),
  lastMoveAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Session = __t.object("Session", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
});
export type Session = __Infer<typeof Session>;

