// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "../accept_friend_request_reducer";
import ConfigureTimingReducer from "../configure_timing_reducer";
import CreateAccountReducer from "../create_account_reducer";
import CreateIslandReducer from "../create_island_reducer";
import DeclineFriendRequestReducer from "../decline_friend_request_reducer";
import DeleteBuildReducer from "../delete_build_reducer";
import EnterIslandReducer from "../enter_island_reducer";
import LeaveIslandReducer from "../leave_island_reducer";
import LoadBuildReducer from "../load_build_reducer";
import MoveReducer from "../move_reducer";
import NewRecoveryCodeReducer from "../new_recovery_code_reducer";
import PlacePieceReducer from "../place_piece_reducer";
import RecoverAccountReducer from "../recover_account_reducer";
import RemoveFriendReducer from "../remove_friend_reducer";
import RemovePieceReducer from "../remove_piece_reducer";
import ResetGameReducer from "../reset_game_reducer";
import RotatePieceReducer from "../rotate_piece_reducer";
import SaveBuildReducer from "../save_build_reducer";
import SendFriendRequestReducer from "../send_friend_request_reducer";
import SetNameReducer from "../set_name_reducer";
import SkipPhaseReducer from "../skip_phase_reducer";
import StartRoundReducer from "../start_round_reducer";
import SubmitIdeaReducer from "../submit_idea_reducer";
import VotePlotReducer from "../vote_plot_reducer";
import VoteThemeReducer from "../vote_theme_reducer";

export type AcceptFriendRequestParams = __Infer<typeof AcceptFriendRequestReducer>;
export type ConfigureTimingParams = __Infer<typeof ConfigureTimingReducer>;
export type CreateAccountParams = __Infer<typeof CreateAccountReducer>;
export type CreateIslandParams = __Infer<typeof CreateIslandReducer>;
export type DeclineFriendRequestParams = __Infer<typeof DeclineFriendRequestReducer>;
export type DeleteBuildParams = __Infer<typeof DeleteBuildReducer>;
export type EnterIslandParams = __Infer<typeof EnterIslandReducer>;
export type LeaveIslandParams = __Infer<typeof LeaveIslandReducer>;
export type LoadBuildParams = __Infer<typeof LoadBuildReducer>;
export type MoveParams = __Infer<typeof MoveReducer>;
export type NewRecoveryCodeParams = __Infer<typeof NewRecoveryCodeReducer>;
export type PlacePieceParams = __Infer<typeof PlacePieceReducer>;
export type RecoverAccountParams = __Infer<typeof RecoverAccountReducer>;
export type RemoveFriendParams = __Infer<typeof RemoveFriendReducer>;
export type RemovePieceParams = __Infer<typeof RemovePieceReducer>;
export type ResetGameParams = __Infer<typeof ResetGameReducer>;
export type RotatePieceParams = __Infer<typeof RotatePieceReducer>;
export type SaveBuildParams = __Infer<typeof SaveBuildReducer>;
export type SendFriendRequestParams = __Infer<typeof SendFriendRequestReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SkipPhaseParams = __Infer<typeof SkipPhaseReducer>;
export type StartRoundParams = __Infer<typeof StartRoundReducer>;
export type SubmitIdeaParams = __Infer<typeof SubmitIdeaReducer>;
export type VotePlotParams = __Infer<typeof VotePlotReducer>;
export type VoteThemeParams = __Infer<typeof VoteThemeReducer>;

